refactor: update wg script

diff --git a/bin/vm_quick_wg_vpn b/bin/vm_quick_wg_vpn
--- a/bin/vm_quick_wg_vpn
+++ b/bin/vm_quick_wg_vpn
@@ -3,7 +3,6 @@
 # Define variables
 WG_CONF_PATH="./wg0.conf"               # Replace with the path to your WireGuard config file
 WG_INTERFACE="wg0"                      # WireGuard interface name
-VPN_DNS="9.9.9.9"                       # Replace with VPN-provided or desired DNS
 PRIVATE_NETWORK_SUBNET="192.168.0.0/16" # Define your private network subnet
 
 # Get default interface and gateway IP
@@ -51,9 +50,9 @@ setup_wireguard() {
   sudo ip route add "$PRIVATE_NETWORK_SUBNET" via "$GATEWAY_IP"
 
   # Check if the WireGuard interface is already up
-  if sudo wg show "$WG_INTERFACE" >/dev/null 2>&1; then
+  if sudo wg show "$WG_INTERFACE" 1>&/dev/null; then
     echo "[INFO] WireGuard interface $WG_INTERFACE is already running. Restarting it."
-    sudo wg-quick down "$WG_INTERFACE" >/dev/null 2>&1
+    sudo wg-quick down "$WG_INTERFACE" 1>&/dev/null
     sleep 2
   fi
 
@@ -69,31 +68,38 @@ setup_wireguard() {
 setup_kill_switch() {
   echo -e "[INFO] Enabling UFW kill switch to prevent traffic leak.\n"
 
-  # Reset UFW and apply basic deny policies
-  sudo ufw disable >/dev/null 2>&1
-  sudo ufw --force reset >/dev/null 2>&1
-
-  sudo ufw default deny outgoing >/dev/null 2>&1
-  sudo ufw default deny incoming >/dev/null 2>&1
-
   # Get WireGuard Endpoint IP and Port from config file
-  WG_ENDPOINT=$(sudo grep -E "^Endpoint" "/etc/wireguard/$WG_INTERFACE.conf" | awk '{print $3}')
-  WG_ENDPOINT_IP=$(echo "$WG_ENDPOINT" | cut -d: -f1)
-  WG_PORT=$(echo "$WG_ENDPOINT" | cut -d: -f2)
+  WG_ENDPOINT=$(sudo grep -E "^Endpoint" "/etc/wireguard/$WG_INTERFACE.conf" | cut -d= -f2)
+  WG_ENDPOINT_IP=$(echo "$WG_ENDPOINT" | cut -d: -f1 | xargs)
+  WG_PORT=$(echo "$WG_ENDPOINT" | cut -d: -f2 | xargs)
+
+  if [[ -z $WG_ENDPOINT_IP || -z $WG_PORT ]]; then
+    echo "[ERROR] No IP and PORT could be found in WG conf file!"
+    exit 1
+  fi
+
+  # Reset UFW and apply basic deny policies
+  sudo ufw disable 1>&/dev/null
+  sudo ufw --force reset 1>&/dev/null
+
+  sudo ufw default deny outgoing 1>&/dev/null
+  sudo ufw default deny incoming 1>&/dev/null
 
   # Allow UDP traffic to WireGuard endpoint IP and port
-  sudo ufw allow out to "$WG_ENDPOINT_IP" port "$WG_PORT" proto udp >/dev/null 2>&1
+  sudo ufw allow out to "$WG_ENDPOINT_IP" port "$WG_PORT" proto udp 1>&/dev/null
   # sudo ufw allow out from any to "$WG_ENDPOINT_IP" port "$WG_PORT" proto udp
 
   # Allow traffic on WireGuard interface
-  sudo ufw allow out on "$WG_INTERFACE" from any to any >/dev/null 2>&1
+  sudo ufw allow out on "$WG_INTERFACE" from any to any 1>&/dev/null
 
   # Allow SSH access over default interface for management
-  sudo ufw allow in on "$DEFAULT_IFACE" to any port 22 proto tcp >/dev/null 2>&1
-  # sudo ufw allow out on "$DEFAULT_IFACE" to 192.168.0.0/16
+  sudo ufw allow in on "$DEFAULT_IFACE" to any port 22 proto tcp 1>&/dev/null
+  sudo ufw allow out on "$DEFAULT_IFACE" to "$PRIVATE_NETWORK_SUBNET" 1>&/dev/null
 
   # Allow DNS requests through the VPN
-  sudo ufw allow out on "$WG_INTERFACE" to "$VPN_DNS" port 53 proto udp >/dev/null 2>&1
+  VPN_DNS=$(sudo grep -E "^DNS" "/etc/wireguard/$WG_INTERFACE.conf" | cut -d= -f2 | cut -d, -f1 | xargs)
+  [[ -z "$VPN_DNS" ]] && VPN_DNS="9.9.9.9"
+  sudo ufw allow out on "$WG_INTERFACE" to "$VPN_DNS" port 53 proto udp 1>&/dev/null
 
   sudo ufw enable
   echo -e "\n[INFO] Kill switch active. All traffic forced through VPN."
