chore: enhance pass helper

diff --git a/zsh/profile2-pass b/zsh/profile2-pass
--- a/zsh/profile2-pass
+++ b/zsh/profile2-pass
@@ -121,6 +121,16 @@ if check_command_q pass; then
     echo "Exported '$pass_name' to '$pass_name'."
   }
 
+  vm_pass_import_secrets_recursiv() {
+    local search_path="${1:-.}"
+    find "$search_path" \
+      -type d \( -name ".password-store" -o -name ".git" \) -prune \
+      -o -type f -print |
+    while read -r file; do
+      vm_pass_import_file "$file"
+    done
+  }
+
   if check_command_q docker; then
     vm_pass_import_docker_secrets() {
       # Find all .env files
@@ -134,66 +144,77 @@ if check_command_q pass; then
       done
     }
 
-    vm_pass_export_docker_secret() {
-      if [ "$#" -lt 2 ]; then
-        echo "Usage: $0 <pass-name> <docker-secret>"
+    vm_pass_export_docker_as_secret() {
+      if [ "$#" -lt 1 ]; then
+        echo "Usage: $0 <docker-secret-name>"
         return 1
       fi
-      local pass_name="$1"
-      local docker_secret="$2"
+      local pass_name
+      local docker_secret="$1"
+
+      pass_name=$(
+        find -L "$prefix" -name "*.gpg" -type f |
+        sed -e "s#${prefix}/\{0,1\}##" -e 's#\.gpg##' -e 's#\\#\\\\#' |
+        fzf --height=~40% --prompt="Select pass entry to export: "
+      )
+      if [ -z "$pass_name" ]; then
+        echo "No entry selected. Export cancelled."
+        return 0
+      fi
+
       pass show "$pass_name" | docker secret create "$docker_secret" - || { echo "Error: Failed to create Docker secret '$docker_secret' from '$pass_name'."; return 1; }
       echo "Docker secret '$docker_secret' created from '$pass_name'."
     }
+  fi
 
-    vm_pass_gpg_export() {
-      local selected_key key_id
+  vm_pass_gpg_export() {
+    local selected_key key_id
 
-      selected_key=$(gpg --list-secret-keys --keyid-format=long --with-colons |
-        awk -F: '
-          $1 == "sec" { key_id = $5 }
-          $1 == "uid" { print key_id, $10 }
-        ' |
-        fzf --height=~40% --cycle --border --prompt="Select GPG key to export: " --footer="Available GPG keys for export")
+    selected_key=$(gpg --list-secret-keys --keyid-format=long --with-colons |
+      awk -F: '
+        $1 == "sec" { key_id = $5 }
+        $1 == "uid" { print key_id, $10 }
+      ' |
+      fzf --height=~40% --cycle --border --prompt="Select GPG key to export: " --footer="Available GPG keys for export")
 
-      if [[ -z "$selected_key" ]]; then
-        echo "No GPG key selected. Export cancelled."
+    if [[ -z "$selected_key" ]]; then
+      echo "No GPG key selected. Export cancelled."
+      return 1
+    fi
+
+    key_id=$(echo "$selected_key" | awk '{print $1}')
+    gpg --export "$key_id" > "${key_id}_public.key" 2>/dev/null || { echo "Error: Failed to export public-key."; return 1; }
+    gpg --pinentry-mode loopback --export-secret-key "$key_id" > "${key_id}_private.key" 2>/dev/null || { echo "Error: Failed to export private-key."; return 1; }
+
+    echo "GPG key pair exported to: ${key_id}_public.key and ${key_id}_private.key"
+  }
+
+  vm_pass_gpg_import() {
+    local public_file private_file key_id
+    local path_to_search="${1:-.}"
+
+    public_file=$(find "$path_to_search" -maxdepth 1 -name "*.key" -type f | fzf --height=~40% --prompt="Select public-key file: ")
+
+    if [[ -n "$public_file" ]]; then
+      key_id=$(gpg --with-colons --import-options show-only --import "$public_file" 2>/dev/null | awk -F: '/^pub:/ {print $5; exit}')
+      if [[ -n "$key_id" ]]; then
+        gpg --import "$public_file" >/dev/null 2>&1 || { echo "Error: Failed to import public-key."; return 1; }
+        printf "trust\n5\ny\nsave\n" | gpg --command-fd 0 --no-tty --no-greeting -q --edit-key "$key_id" >/dev/null 2>&1
+        echo "GPG public-key imported successfully and trust set to 'ultimate'."
+      else
+        echo "Error: Could not determine key ID from public-key file."
         return 1
       fi
+    else
+      echo "GPG public-key import skipped. No public-key file selected."
+    fi
 
-      key_id=$(echo "$selected_key" | awk '{print $1}')
-      gpg --export "$key_id" > "${key_id}_public.key" 2>/dev/null || { echo "Error: Failed to export public-key."; return 1; }
-      gpg --pinentry-mode loopback --export-secret-key "$key_id" > "${key_id}_private.key" 2>/dev/null || { echo "Error: Failed to export private-key."; return 1; }
-
-      echo "GPG key pair exported to: ${key_id}_public.key and ${key_id}_private.key"
-    }
-
-    vm_pass_gpg_import() {
-      local public_file private_file key_id
-      local path_to_search="${1:-.}"
-
-      public_file=$(find "$path_to_search" -maxdepth 1 -name "*.key" -type f | fzf --height=~40% --prompt="Select public-key file: ")
-
-      if [[ -n "$public_file" ]]; then
-        key_id=$(gpg --with-colons --import-options show-only --import "$public_file" 2>/dev/null | awk -F: '/^pub:/ {print $5; exit}')
-        if [[ -n "$key_id" ]]; then
-          gpg --import "$public_file" >/dev/null 2>&1 || { echo "Error: Failed to import public-key."; return 1; }
-          printf "trust\n5\ny\nsave\n" | gpg --command-fd 0 --no-tty --no-greeting -q --edit-key "$key_id" >/dev/null 2>&1
-          echo "GPG public-key imported successfully and trust set to 'ultimate'."
-        else
-          echo "Error: Could not determine key ID from public-key file."
-          return 1
-        fi
-      else
-        echo "GPG public-key import skipped. No public-key file selected."
-      fi
-
-      private_file=$(find . -maxdepth 1 -name "*.key" -type f | fzf --height=~40% --prompt="Select private-key file: ")
-      if [[ -n "$private_file" ]]; then
-        gpg --pinentry-mode loopback --import "$private_file" >/dev/null 2>&1 || { echo "Error: Failed to import private-key."; return 1; }
-        echo "GPG private-key imported successfully."
-      else
-        echo "GPG private-key import skipped. No private-key file selected."
-      fi
-    }
-  fi
+    private_file=$(find . -maxdepth 1 -name "*.key" -type f | fzf --height=~40% --prompt="Select private-key file: ")
+    if [[ -n "$private_file" ]]; then
+      gpg --pinentry-mode loopback --import "$private_file" >/dev/null 2>&1 || { echo "Error: Failed to import private-key."; return 1; }
+      echo "GPG private-key imported successfully."
+    else
+      echo "GPG private-key import skipped. No private-key file selected."
+    fi
+  }
 fi
